### ISSUE TITLE
Relevant to track newer Rails versions?

### ISSUE THREAD

**Issue by rud** [presidentbeef/inject-some-sql#4]
Hi,

I've referred a bunch of people http://rails-sqli.org through the years, it's a visceral experience for most (followed quickly by some frantic commits). 

Would it be relevant to update it to document behaviour in Rails 4.2+ versions? Do you think it would be a tricky upgrade, or should it be an easy enough first contribution?

**Comment by presidentbeef** [comment]
Yes, I think it would be very useful. I would like to split the page so Rails 3 and Rails 4 are separate, since some methods have the same name but different behavior in different versions. Unfortunately it's a bit of a pain because the site is currently generated by running the Rails app, visiting the examples page, then copying the HTML via wget, modifying the HTML, and finally committing that HTML. Then doing the same with the rails4 branch but just copying the relevant queries...

Upgrading from Rails 4.0.3 seems a little hard. It would likely be easier to create a new Rails 4.2 app, copy the queries, and go from there.

If you have suggestions on how to do this better, please feel free :)

**Comment by rud** [comment]
Hmm, if you have a bunch of `wget` invocations, maybe wrap it all up in a `rake`-task so you can easily re-run it after an edit? Just an idea.

**Comment by rud** [comment]
"Modifying the HTML" -> should probably be scripted too, but one step at a time would probably be a good idea

**Comment by rud** [comment]
Closing this out - but feel free to loop me in if you have concrete questions in how something could be automated
